### PR TITLE
Merge master into teams

### PR DESCRIPTION
**Pull request by rouson**
@scrasmussen I'm attempting to update the teams branch to reflect the latest changes in the master branch (which I just updated to add the latest commits from the GCC git mirror).  Could you resolve the resulting conflicts?  Presumably they relate to recent commits you or @fanfa have made on the teams branch.

### CODE REVIEW

**Comment by scrasmussen** [comment]
@rouson Accidentally merged the teams branch into the master. Working on undoing that right now.

**Comment by zbeekman** [comment]
@scrasmussen if you need git help let me know. You should be able to do a hard reset and forced push to fix it. Feel free to gchat/video call or get a hold of me through slack

**Comment by scrasmussen** [comment]
@zbeekman Thanks, I got it sorted out. Used the 'git revert -m 1 [commit number]' command. It undoes the commit but leaves it in the commit history as a public shaming so I don't do it again ; )

**Comment by zbeekman** [comment]
@scrasmussen: In general I approve of your technique.

Sometimes reverted merges can cause complications later if a merge between the original two branches is attempted again, at a later point in git history. We can deal with this later, if we try to perform the merge. The bottom line is that merging teams into master at a later date won't contain the commits that have been reverted unless additional steps are taken.

Since you have reverted master already, merged it into teams, and `master` is no longer strictly tracking upstream since @rouson added a markdown README etc. I think the best course of action is to leave things as they are.

**Pull request merged**
